version: '3.8'

services:
  social-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080" # Expose port 8080 for internal Docker network communication
    environment:
      - EXPO_PUBLIC_PDS_URL=https://pds.bigt.ai
      - EXPO_PUBLIC_APPVIEW_URL=https://appview.bigt.ai
    networks:
      - app-network

  bsky-pds:
    image: ghcr.io/bluesky-social/pds:latest # Placeholder, replace with actual PDS image/build
    ports:
      - "8080" # Internal port for PDS
    environment:
      - PDS_HOSTNAME=bsky-pds
      - PDS_PUBLIC_URL=http://localhost:8080 # Or your domain for external access
      # Add other necessary PDS environment variables (e.g., database, JWT secrets)
    networks:
      - app-network

  bsky-appview:
    image: ghcr.io/bluesky-social/appview:latest # Placeholder, replace with actual AppView image/build
    ports:
      - "8080" # Internal port for AppView
    environment:
      - APPVIEW_HOSTNAME=bsky-appview
      - APPVIEW_PUBLIC_URL=http://localhost:8080 # Or your domain for external access
      - APPVIEW_PDS_URL=http://bsky-pds:8080 # Point to the local PDS service
      # Add other necessary AppView environment variables (e.g., database, JWT secrets)
    depends_on:
      - bsky-pds
    networks:
      - app-network

  caddy:
    image: caddy:2.7.6-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - social-app
      - bsky-pds # Caddy depends on PDS and AppView for a full stack
      - bsky-appview
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
